### ISSUE TITLE
getting 404 error while trying npm install

### ISSUE THREAD

**Issue by krishpranav** [Andino-Labs/yiqi-mobile#2]
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@andino-labs%2fyiqi-client - Not found
npm ERR! 404
npm ERR! 404  '@andino-labs/yiqi-client@^1.0.8' is not in this registry.
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mypc/.npm/_logs/2024-12-03T10_39_38_017Z-debug-0.log

**Comment by krishpranav** [comment]
I got the repo from linkedin. https://www.linkedin.com/jobs/view/4090001636/

I am looking to work with you guys

Thanks

**Comment by djimi007** [comment]
i had the same issue

**Comment by krishpranav** [comment]
I think so they have some packages private, we need that packages in-order to develop the functionalities which are listed.

**Comment by pbrain19** [comment]
https://github.com/Andino-Labs/yiqi-mobile/blob/main/.npmrc.example

**Comment by djimi007** [comment]
can you provide more information where we can find "authToken"

**Comment by djimi007** [comment]
can you provide more information please where we can find "authToken" ???

**Comment by krishpranav** [comment]
thanks for giving the solution, closing this issue
